# Codecov configuration
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        informational: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "vendor/"
  - "database/"
  - "storage/"
  - "bootstrap/"
  - "config/"
