name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:
  pull_request:
    branches: [ main, agent, develop ]

permissions:
  contents: read
  security-events: write

jobs:
  backend-audit:
    name: Backend Security Audit
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run Composer Audit
        run: composer audit --no-dev
        continue-on-error: true

      - name: Run Composer Security Check
        uses: Roave/security-advisories-composer-action@master
        continue-on-error: true

  frontend-audit:
    name: Frontend Security Audit
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run NPM Audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Run NPM Audit (Production)
        run: npm audit --production --audit-level=high
        continue-on-error: true

  code-scanning:
    name: CodeQL Analysis
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 30
    if: github.event_name != 'pull_request'

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'php' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-24.04-arm
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review (PHP)
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

      - name: Dependency Review (JavaScript)
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
        working-directory: frontend
